# Generated by Django 4.2.2 on 2023-06-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(default='', max_length=240, null=True)),
                ('company_name', models.CharField(max_length=240, null=True)),
                ('phone', models.CharField(max_length=240, null=True)),
                ('location', models.CharField(max_length=240, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
