# Generated by Django 4.2.2 on 2023-06-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='property_id',
            new_name='property_code',
        ),
    ]
