# Generated by Django 4.2.2 on 2023-07-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_owners_details_owners_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, null=True)),
                ('userid', models.CharField(max_length=240, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('encodede', models.CharField(max_length=240, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
