# Generated by Django 4.2.2 on 2023-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_company_credentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_credentials',
            old_name='encodede',
            new_name='email',
        ),
        migrations.AddField(
            model_name='company_credentials',
            name='mobile',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
