# Generated by Django 4.2.2 on 2023-07-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_civil_defence_document_main_documents_files_main_file_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_dates', models.CharField(max_length=240, null=True)),
                ('last_sent', models.DateField(max_length=240, null=True)),
            ],
        ),
    ]
