# Generated by Django 4.2.2 on 2023-07-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_admin_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_datas',
            name='last_sent',
            field=models.DateField(default='2000-08-23', max_length=240, null=True),
        ),
    ]
