# Generated by Django 4.2.2 on 2023-07-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_admin_datas_last_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=240, null=True)),
                ('mobile', models.CharField(max_length=240, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='Staff/Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Passports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.FileField(blank=True, null=True, upload_to='Staff/Passport')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff_details')),
            ],
        ),
    ]
