# Generated by Django 4.2.2 on 2023-07-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_staff_details_staff_passports'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_details',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
