# Generated by Django 4.2.2 on 2023-07-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_staff_details_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Doc_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_documetfile', models.FileField(blank=True, null=True, upload_to='Staff/Documents')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_documetname', models.CharField(max_length=240, null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff_details')),
            ],
        ),
        migrations.DeleteModel(
            name='Staff_Passports',
        ),
        migrations.AddField(
            model_name='staff_doc_files',
            name='staff_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff_docs'),
        ),
    ]
