# Generated by Django 4.2.2 on 2023-07-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_staff_doc_files_staff_docs_delete_staff_passports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_docs',
            name='s_documetexp',
            field=models.DateField(max_length=240, null=True),
        ),
    ]
